### ISSUE TITLE
Fix ALL installation issues: w3af @ docker?

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#2612]
Fix ALL installation issues: w3af @ docker?

**Comment by Wenzel** [comment]
Hello, i tried to build w3af with the Dockerfile provided in extras/ and I get the following output

~~~
Setting up g++-4.6 (4.6.3-1ubuntu5) ...
Setting up g++ (4:4.6.3-1ubuntu5) ...
update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode.
Setting up build-essential (11.5ubuntu2.1) ...
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
Collecting clamd==1.0.1
  Downloading clamd-1.0.1.zip
    Installed /tmp/pip-build-AToFel/clamd/.eggs/d2to1-0.2.11-py2.7.egg
    [d2to1] running patched manifest_maker command with extra_files support
    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
        func(*targs, **kargs)
      File "/usr/lib/python2.7/multiprocessing/util.py", line 284, in _exit_function
        info('process shutting down')
    TypeError: 'NoneType' object is not callable
    Error in sys.exitfunc:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
        func(*targs, **kargs)
      File "/usr/lib/python2.7/multiprocessing/util.py", line 284, in _exit_function
        info('process shutting down')
    TypeError: 'NoneType' object is not callable
Collecting PyGithub==1.21.0
  Downloading PyGithub-1.21.0.tar.gz (2.3MB)
Collecting GitPython==0.3.2.RC1
  Downloading GitPython-0.3.2.RC1.tar.gz (313kB)
    /usr/local/lib/python2.7/dist-packages/setuptools/dist.py:292: UserWarning: The version specified ('0.3.2 RC1') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
      "details." % self.metadata.version
Collecting pybloomfiltermmap==0.3.11
  Downloading pybloomfiltermmap-0.3.11.tar.gz (435kB)
    info: Building from C
Collecting esmre==0.3.1
  Downloading esmre-0.3.1.tar.gz
Collecting phply==0.9.1
  Downloading phply-0.9.1.tar.gz
Collecting nltk==2.0.4
  Downloading nltk-2.0.4.tar.gz (955kB)
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Extracting in /tmp/tmpqlHk35
    Now working in /tmp/tmpqlHk35/distribute-0.6.21
    Building a Distribute egg in /tmp/pip-build-AToFel/nltk
    /tmp/pip-build-AToFel/nltk/distribute-0.6.21-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-AToFel/nltk/setup.py", line 32, in <module>
        del sdist.finders[:]
    AttributeError: 'module' object has no attribute 'finders'
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    
    Extracting in /tmp/tmpqlHk35
    
    Now working in /tmp/tmpqlHk35/distribute-0.6.21
    
    Building a Distribute egg in /tmp/pip-build-AToFel/nltk
    
    /tmp/pip-build-AToFel/nltk/distribute-0.6.21-py2.7.egg
    
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-AToFel/nltk/setup.py", line 32, in <module>
    
        del sdist.finders[:]
    
    AttributeError: 'module' object has no attribute 'finders'
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-AToFel/nltk
~~~

The script generated `/tmp/w3af_dependency_install.sh` tries to install very specific versions of python module and it's not working.

the following procedure works to run w3af_console in Docker :

- remove all `==x.x.x` in `/tmp/w3af_dependency_install.sh`
- install package `libffi-dev`
- run `/tmp/w3af_dependency_install.sh`
- install python module `six`
- remove the dependency check (`w3af_console line 13 -> dependency_check()` )

now `./w3af_console` should be working.

**Comment by andresriancho** [comment]
I got a couple of questions about what you did:
 * Which branch are you testing this on? If it's not `aking1012-develop` then please try again there
 * libffi-dev tells me you're testing this in develop?
 * Not sure why you need the `six` package, any ideas on which pip package requested that?

**Comment by Wenzel** [comment]
I was on `master` before.
I tried on your branch, `aking1012-develop`

`apt-get install libffi-dev` is required because of the following error when installing python modules

~~~
Collecting enum34 (from cryptography>=0.2.1->pyOpenSSL)
  Downloading enum34-1.0.4.tar.gz
Collecting pycparser (from cffi>=0.8->cryptography>=0.2.1->pyOpenSSL)
  Downloading pycparser-2.10.tar.gz (206kB)
    100% |################################| 208kB 30.6MB/s 
Installing collected packages: pycparser, enum34, pyasn1, cffi, smmap, six, cryptography, ply, gitdb, darts.util.lru, halberd, python-ntlm, msgpack-python, cluster, guess-language, scapy-real, pyOpenSSL, futures, pdfminer, chardet, nltk, phply, esmre, pybloomfiltermmap, GitPython, PyGithub, clamd
  Running setup.py install for pycparser
  Running setup.py install for enum34
  Running setup.py install for pyasn1
  Running setup.py install for cffi
    building '_cffi_backend' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
    c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-G1bAK4/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-FsZLTx-record/install-record.txt --single-version-externally-managed --compile:
    running install
    
    running build
    
    running build_py
    
    creating build
    
    creating build/lib.linux-x86_64-2.7
    
    creating build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/vengine_gen.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/ffiplatform.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/api.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/gc_weakref.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/__init__.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/model.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/commontypes.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/lock.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/verifier.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/cparser.py -> build/lib.linux-x86_64-2.7/cffi
    
    running build_ext
    
    building '_cffi_backend' extension
    
    creating build/temp.linux-x86_64-2.7
    
    creating build/temp.linux-x86_64-2.7/c
    
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
    
    c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
    
    compilation terminated.
~~~

The header `ffi.h` was missing to compile a module.

This time i had a different error when running `./w3af_console`.
~~~
Error while reading plugin options: "There was an error while importing w3af.plugins.grep.cache_control: "cannot import name process_pdf"."
~~~

**Comment by Wenzel** [comment]
Ok, forget about my last comment, I didn't rebuild the container from scratch :)
it's working now.
thx

**Comment by Wenzel** [comment]
Ok, forget about my last comment, I didn't rebuild the container from scratch with the new Dockerfile.

now I have an error at the `line 47` of your Dockerfile : `RUN git checkout feature/stopit`
`error: pathspec 'feature/stopit' did not match any file(s) known to git.`

**Comment by andresriancho** [comment]
try to change that line to `RUN git checkout develop`

**Comment by Wenzel** [comment]
Ok the container builds without any problem.
when i run `./w3af_console` in the container, i have this error
~~~
Exception in thread PoolTaskHandler:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
TypeError: _handle_tasks() takes exactly 4 arguments (5 given)
~~~

**Comment by andresriancho** [comment]
Thanks for your details, will try to fix this before the 1.6.50 release. If you've got some minutes could you try to identify and fix the issue?

**Comment by Wenzel** [comment]
I tried to rebuild your container from scratch on branch `aking1012-develop`.
- you have to change the line 47 :  `RUN git checkout feature/stopit` to `RUN git checkout develop`.

The exception is raised in `/usr/lib/python2.7/threading.py`, so it's seems to be linked to the python `threading` module.
I'm not a Python programmer, so i don't know to debug this, sorry.

**Comment by andresriancho** [comment]
Ok, no problem, I'll check it out

**Comment by andresriancho** [comment]
I was able to reproduce the issue:

```
[pablo:/home/pablo/pch/w3af/extras] develop(+2/-1) ± sudo docker run --interactive --tty 65ec1efc453c
Checking if a new version is available in our git repository. Please wait...
An error occurred while updating: "An error occurred while fetching from the remote Git repository! Please update manually using "git pull"."
Usage of w3af for sending any traffic to a target without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program.

Do you accept the terms and conditions? [N|y] y
Exception in thread PoolTaskHandler:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
TypeError: _handle_tasks() takes exactly 4 arguments (5 given)

w3af>>> 

```

**Comment by andresriancho** [comment]
In python 2.7.6 (which is what I'm using for dev) we see this:

```python
        self._task_handler = threading.Thread(
            target=Pool._handle_tasks,
            args=(self._taskqueue, self._quick_put, self._outqueue,
                  self._pool, self._cache)
            )
```

But in python 2.7.3, which is what gets installed inside the docker image we see:

```python
        self._task_handler = threading.Thread(
            target=Pool._handle_tasks,
            args=(self._taskqueue, self._quick_put, self._outqueue, self._pool)
            )
        self._task_handler.daemon = True
        self._task_handler._state = RUN
        self._task_handler.start()
```

w3af overrides the code that inits the `self._task_handler`, but it's made to work with 2.7.6, not with 2.7.3. Looks like I'll have to override more stuff.

This problem is **not related with docker**, we just found it there but it could have been in any other place. Created https://github.com/andresriancho/w3af/issues/8368 to fix it

**Comment by andresriancho** [comment]
TODOs for closing this issue:
 - [ ] https://github.com/andresriancho/w3af/blob/aking1012-develop/extras/Dockerfile#L47
   - [ ] I need to do it with "ADD .", if I get the issue of not being able to add ".." create a script that will move the dockerfile to w3af's root and build it there
 - [ ] Add docker console documentation
 - [ ] If I can't make it work in 15min, add a note to the README.md saying that I need help with the GUI part
 - [ ] Merge to aking's branch to develop

**Comment by andresriancho** [comment]
Related issues:
 * Allow w3af_console_docker parameter forwarding #8461
 * Docker GUI run #8460

**Comment by andresriancho** [comment]
No more automated builds: https://github.com/andresriancho/w3af/commit/367a8e4b1c25e13509bedb29cd23a17283f57b40

**Comment by wangjian2014** [comment]
Hello,I execute the command.
extras/docker/scripts# ./w3af_gui_docker
I get result
Unable to find image 'andresriancho/w3af:latest' locally
Pulling repository andresriancho/w3af
time="2015-05-28T19:57:42-07:00" level=fatal msg="Tag latest not found in repository andresriancho/w3af" 
w3af container failed to start: "Command 'docker run -d -v ~/.w3af:/root/.w3af -v ~/w3af-shared:/root/w3af-shared andresriancho/w3af' returned non-zero exit status 1"

How can I resolve this problem? thank you

**Comment by andresriancho** [comment]
@wangjian2014 applied a fix, please test in `develop` branch.

Note: The docker+w3af+GUI isn't working (at least for me) please test the console

**Comment by gustavofulton** [comment]
Hey. I've been having a similar issue. This is what I get when trying to install the dependencies at /tmp/w3af_dependency_install.sh. 

Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-059YP_/pybloomfiltermmap/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-gJi0Vp-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-059YP_/pybloomfiltermmap

**Comment by andresriancho** [comment]
@gustavofulton you're having that problem with our docker image? If not, please create a different ticket with all the info as explained in http://docs.w3af.org/en/latest/report-a-bug.html
