### ISSUE TITLE
Cant install nltk

### ISSUE THREAD

**Issue by bigdaddy51** [andresriancho/w3af#7713]
Cant install nltk Please Help!!!

Mac os x 10.9.5

Terminal Output********************

Russells-Mac-Pro:w3af mojo$ sudo -H /var/folders/gf/92ccbldn22d1jc6jxh3qx9940000gn/T/w3af_dependency_install.sh
Requirement already satisfied (use --upgrade to upgrade): clamd==1.0.1 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): PyGithub==1.21.0 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): GitPython==0.3.2.RC1 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pybloomfiltermmap==0.3.11 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): esmre==0.3.1 in /Library/Python/2.7/site-packages
Collecting nltk==2.0.4
  Using cached nltk-2.0.4.tar.gz
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Extracting in /tmp/tmpvn1gbz
    Now working in /tmp/tmpvn1gbz/distribute-0.6.21
    Building a Distribute egg in /private/tmp/pip-build-RYbEHJ/nltk
    /private/tmp/pip-build-RYbEHJ/nltk/distribute-0.6.21-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-RYbEHJ/nltk/setup.py", line 32, in <module>
        del sdist.finders[:]
    AttributeError: 'module' object has no attribute 'finders'
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    
    Extracting in /tmp/tmpvn1gbz
    
    Now working in /tmp/tmpvn1gbz/distribute-0.6.21
    
    Building a Distribute egg in /private/tmp/pip-build-RYbEHJ/nltk
    
    /private/tmp/pip-build-RYbEHJ/nltk/distribute-0.6.21-py2.7.egg
    
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-RYbEHJ/nltk/setup.py", line 32, in <module>
    
        del sdist.finders[:]
    
    AttributeError: 'module' object has no attribute 'finders'
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-RYbEHJ/nltk

sudo pip install clamd==1.0.1 PyGithub==1.21.0 GitPython==0.3.2.RC1 pybloomfiltermmap==0.3.11 esmre==0.3.1 nltk==2.0.4 chardet==2.1.1 pdfminer==20110515 futures==2.1.5 pyOpenSSL==0.13.1 scapy-real==2.2.0-dev guess-language==0.2 cluster==1.1.1b3 msgpack-python==0.2.4 python-ntlm==1.0.1 halberd==0.2.4 darts.util.lru==0.5

Russells-Mac-Pro:w3af mojo$ pip freeze | grep nltk
nltk==3.0.1

Russells-Mac-Pro:w3af mojo$ python --version
Python 2.7.9

**Comment by andresriancho** [comment]
See https://github.com/nltk/nltk/issues/824

You might need to use the `develop` branch to workaround this issue/use the latest nltk
