### ISSUE TITLE
Problem installing w3af SSL_ST_INIT = _lib.SSL_ST_INIT

### ISSUE THREAD

**Issue by C2vsh2nk2** [andresriancho/w3af#14895]
Hi everyone,

upon running the following command, i am not able to fix the problem:

```
$ ./w3af_console
Traceback (most recent call last):
  File "./w3af_console", line 15, in <module>
    from w3af.core.ui.console.console_ui import ConsoleUI
  File "/root/w3af/w3af/core/ui/console/console_ui.py", line 35, in <module>
    from w3af.core.ui.console.rootMenu import rootMenu
  File "/root/w3af/w3af/core/ui/console/rootMenu.py", line 32, in <module>
    from w3af.core.ui.console.plugins import pluginsMenu
  File "/root/w3af/w3af/core/ui/console/plugins.py", line 29, in <module>
    from w3af.core.ui.console.config import ConfigMenu
  File "/root/w3af/w3af/core/ui/console/config.py", line 27, in <module>
    from w3af.core.controllers.plugins.plugin import Plugin
  File "/root/w3af/w3af/core/controllers/plugins/plugin.py", line 37, in <module>
    from w3af.core.data.url.helpers import new_no_content_resp
  File "/root/w3af/w3af/core/data/url/helpers.py", line 28, in <module>
    import OpenSSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
```
I have already read the other posts about the problems. Most of the answer claim that the bug is fixed in the current w3af version. Any ideas?

Best greetings

Some output:
```

$ uname -a
Linux ? 4.8.0-1-amd64 #1 SMP Debian 4.8.7-1 (2016-11-13) x86_64 GNU/Linux

$ ./w3af_dependency_install.sh 
Requirement already satisfied: pyOpenSSL==0.15.1 in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: six>=1.5.2 in /usr/lib/python2.7/dist-packages (from pyOpenSSL==0.15.1)
Requirement already satisfied: cryptography>=0.7 in /usr/local/lib/python2.7/dist-packages (from pyOpenSSL==0.15.1)
Requirement already satisfied: setuptools>=11.3 in /usr/lib/python2.7/dist-packages (from cryptography>=0.7->pyOpenSSL==0.15.1)
Requirement already satisfied: ipaddress in /usr/lib/python2.7/dist-packages (from cryptography>=0.7->pyOpenSSL==0.15.1)
Requirement already satisfied: pyasn1>=0.1.8 in /usr/local/lib/python2.7/dist-packages (from cryptography>=0.7->pyOpenSSL==0.15.1)
Requirement already satisfied: enum34 in /usr/lib/python2.7/dist-packages (from cryptography>=0.7->pyOpenSSL==0.15.1)
Requirement already satisfied: idna>=2.0 in /usr/lib/python2.7/dist-packages (from cryptography>=0.7->pyOpenSSL==0.15.1)
Requirement already satisfied: cffi>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography>=0.7->pyOpenSSL==0.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.4.1->cryptography>=0.7->pyOpenSSL==0.15.1)

$ pip freeze
apt-xapian-index==0.49
argcomplete==1.7.0
argh==0.26.2
attrs==16.3.0
backports-abc==0.5
backports.ssl-match-hostname==3.5.0.1
beautifulsoup4==4.4.1
blinker==1.4
Brotli==0.5.2
bzr==2.8.0.dev1
CDDB==1.4
certifi==2016.9.26
cffi==1.9.1
chardet==2.1.1
click==6.6
cluster==1.1.1b3
colorama==0.3.7
ConfigArgParse==0.11.0
configobj==5.0.6
construct==2.5.2
cryptography==1.7.1
cssutils==1.0
darts.util.lru==0.5
dirspec==13.10
dnspython==1.15.0
Dockbarx==0.92
docutils==0.13.1
enum34==1.1.6
esmre==0.3.1
feedparser==5.1.3
Flask==0.10.1
FormEncode==1.3.0
funcsigs==1.0.2
functools32==3.2.3.post2
futures==2.1.5
gfceux===2.2svn
gitdb==0.6.4
gitdb2==2.0.0
GitPython==0.3.2rc1
guess-language==0.2
guess-language-spirit==0.5.2
h2==2.4.1
halberd==0.2.4
hpack==2.3.0
html2text==2016.9.19
html5lib==1.0b8
httplib2==0.9.2
hyperframe==3.2.0
idna==2.1
ipaddr==2.1.11
ipaddress==1.0.17
itsdangerous==0.24
Jinja2==2.7.3
jsbeautifier==1.6.4
jsonschema==2.5.1
keyring==10.1
keyrings.alt==1.3
launchpadlib==1.10.4
lazr.restfulclient==0.13.4
lazr.uri==1.0.3
lockfile==0.12.2
Logbook==0.12.3
lxml==3.4.4
Markdown==2.6.1
MarkupSafe==0.23
mitmproxy==0.13
mock==2.0.0
msgpack-python==0.4.4
mutagen==1.34.1
ndg-httpsclient==0.3.3
netifaces==0.10.4
netlib==0.13.1
nltk==3.0.1
numpy==1.12.0b1
oauth==1.0.1
passlib==1.7.0
Paste==2.0.3
pathtools==0.1.2
pbr==1.10.0
pdfminer==20140328
phply==0.9.1
Pillow==3.4.2
pluginbase==0.3
ply==3.9
psutil==2.2.1
pyalsaaudio==0.7
pyasn1==0.1.8
pyasn1-modules==0.0.7
pybloomfiltermmap==0.3.14
pyClamd==0.3.15
pycparser==2.17
pycrypto==2.6.1
pycurl==7.43.0
pyenchant==1.6.7
PyGithub==1.21.0
Pygments==2.1.3
pygobject==3.22.0
pygpgme==0.3
pyinotify==0.9.6
pyliblzma==0.5.3
pyOpenSSL==0.15.1
pyparsing==2.1.10
pyperclip==1.5.27
pysqlite==1.0.1
python-apt==1.1.0b5
python-daemon==2.1.1
python-dateutil==2.5.3
python-debian==0.1.29
python-debianbts==2.6.1
python-musicbrainz2==0.7.4
python-ntlm==1.0.1
python-openid==2.2.5
python-xlib==0.14
pyxdg==0.25
PyYAML==3.11
pyzmq==16.0.2
quodlibet==3.7.0
reportbug==6.6.6
repoze.lru==0.6
requests==2.12.4
roman==2.0.0
Routes==2.3.1
rpm-python==4.12.0.2
ruamel.ordereddict==0.4.8
scapy===unknown.version
scapy-real==2.2.0.dev0
scgi==1.13
scrypt==0.6.1
SecretStorage==2.3.1
service-identity==16.0.0
simplejson==3.10.0
singledispatch==3.4.0.3
six==1.10.0
smmap==0.9.0
smmap2==2.0.1
srp==1.0.4
tblib==0.2.0
Tempita==0.5.2
termcolor==1.1.0
tldextract==1.7.2
tornado==4.4.2
typing==3.5.2.2
urlgrabber==3.10.1
urllib3==1.19.1
urwid==1.3.1
uTidylib==0.3
virtualenv==15.1.0
vulndb==0.0.19
wadllib==1.3.2
wafw00f==0.9.4
watchdog==0.8.3
webencodings==0.5
WebOb==1.6.2
Werkzeug==0.11.11
Whoosh==2.7.0
xdot==0.6
yum-metadata-parser==1.1.4
zope.interface==4.3.2
zope.proxy==4.2.0

$ python --version
Python 2.7.13

$ pip install --upgrade pyopenssl
Collecting pyopenssl
  Using cached pyOpenSSL-16.2.0-py2.py3-none-any.whl
Requirement already up-to-date: cryptography>=1.3.4 in /usr/local/lib/python2.7/dist-packages (from pyopenssl)
Requirement already up-to-date: six>=1.5.2 in /usr/lib/python2.7/dist-packages (from pyopenssl)
Requirement already up-to-date: setuptools>=11.3 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4->pyopenssl)
Requirement already up-to-date: ipaddress in /usr/lib/python2.7/dist-packages (from cryptography>=1.3.4->pyopenssl)
Collecting pyasn1>=0.1.8 (from cryptography>=1.3.4->pyopenssl)
  Using cached pyasn1-0.1.9-py2.py3-none-any.whl
Requirement already up-to-date: enum34 in /usr/lib/python2.7/dist-packages (from cryptography>=1.3.4->pyopenssl)
Requirement already up-to-date: idna>=2.0 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4->pyopenssl)
Requirement already up-to-date: cffi>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4->pyopenssl)
Requirement already up-to-date: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.4.1->cryptography>=1.3.4->pyopenssl)
Installing collected packages: pyopenssl, pyasn1
  Found existing installation: pyOpenSSL 0.15.1
    Uninstalling pyOpenSSL-0.15.1:
      Successfully uninstalled pyOpenSSL-0.15.1
  Found existing installation: pyasn1 0.1.8
    Uninstalling pyasn1-0.1.8:
      Successfully uninstalled pyasn1-0.1.8
Successfully installed pyasn1-0.1.9 pyopenssl-16.2.0

```

**Comment by c3stbon** [comment]
i had the same problem

**Comment by musicmancorley** [comment]
Hi everyone.  Here's what I did to resolve this.  I first opened python and made certain I could import OpenSSL without any errors.
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import OpenSSL
>>> 
  Once that was confirmed, I simply opened w3af_gui and commended out these two lines and saved the file. 

#from w3af.core.ui.gui.dependency_check.dependency_check import dependency_check
#dependency_check()
now try: ./w3af_gui
assuming you have all the dependencies, this worked for me.  The script kept insisting I did not, even though I knew I did.  hope this helps someone

**Comment by andresriancho** [comment]
The dependency check script seems to be generating problems (again). I need to think about a way to let users bypass it.

```
./w3af_console --no-dependency-check
```

Or similar would work.

**Comment by iLuaCT0** [comment]
1:
Exec this cmd
pip uninstall pyOpenSSL

2:
Exec this cmd
pip install pyOpenSSL

3:
Now go to
....XXXX/w3af/w3af/core/controllers/dependency_check/requirements.py
and edit the python file
on line 39 is write:
PIPDependency('OpenSSL', 'pyOpenSSL', '0.15.1'),
Modify it to
PIPDependency('OpenSSL', 'pyOpenSSL', '16.2.0'),
OR
PIPDependency('OpenSSL', 'pyOpenSSL', 'Version of pyOpenSSL you are using'),

Sorry for my bad english.

**Comment by YongHaoWu** [comment]
@iLuaCT0 Thanks. It works!

**Comment by cr4shboy** [comment]
**Not a solution**, just precaution for someone facing the kind of problem, when pip just refuses to execute:

_./w3af_dependency_install.sh_ replaces newer _pyOpenSSL_ f.e. 16.2.0 with w3af required _pyOpenSSL==0.15.1_ and so the python's pip fails and then there is no easy way to remove package then, using _pip uninstall pyOpenSSL_ (pip just don't works ;)) )

So before blindly executing _./w3af_dependency_install.sh_, check the version of _pyOpenSSL_ using 
> pip list | grep pyOpenSSL

and correct _w3af/core/controllers/dependency_check/requirements.py_ file's line: _PIPDependency('OpenSSL', 'pyOpenSSL', '0.15.1')_ to number grep will expose (16.2.0) f.e.

**Comment by xperblueray** [comment]
I can't run any pip <anything>,so anyone have any idea to solve this problem?

**Comment by guysmileyy** [comment]
This is the solution. https://www.linkedin.com/pulse/solution-attributeerror-module-object-has-attribute-sslstinit-karnad  

You need to ~~~~ $ sudo rm -rf /usr/local/lib/python2.7/dist-packages/OpenSSL/
Then python -m easy_install --upgrade pyOpenSSL to reinstall the newer version.

**Comment by bluszcz** [comment]
Same problem while trying to launch w3af within OSX.

**Comment by julio99OK** [comment]
**guysmileyy** thanks realy thanks you...it works

**Comment by tarasvaskiv** [comment]
I had the same issue after bin/buildout -N    and trying to fire up chaussette.

**Comment by andresriancho** [comment]
Solved with the latest commit to master I made today

**Comment by vhosakot** [comment]
I saw the `AttributeError: 'module' object has no attribute 'SSL_ST_INIT'` error too and `sudo pip install pyOpenSSL==16.2.0` resolved it for me!

**Comment by jamesacampbell** [comment]
For me, working in Python3.6, I had to remove `sudo rm -rf /usr/local/lib/python3.6/site-packages/OpenSSL`
